### ISSUE TITLE
Document how to overwrite solrconfig.xml and schema.xml

### ISSUE THREAD

**Issue by sobrinho** [makuk66/docker-solr#10]
These files should be replaced with custom files when using sunspot solr on rails.

How can we make it work?

**Comment by makuk66** [comment]
@sobrinho have a look at https://github.com/makuk66/docker-solr/commit/6849cf652cd694cae8ae5048125e831eae9f172c to see if that technique applies here.

**Comment by Unknown-Guy** [comment]
Create new docker file with:

```
FROM makuk66/docker-solr

COPY solr/configsets/sunspot /opt/solr/server/solr/configsets/sunspot
```

Take the configsets directory from https://github.com/sunspot/sunspot/tree/master/sunspot_solr/solr/solr

And then just

``` bash
docker build -t db_solr -f $DOCKER_PATH/solr/Dockerfile $DOCKER_PATH
docker run -d -p 8983:8983 --name solr db_solr
docker exec -it --user=solr solr bin/solr create_core -c development -d sunspot
docker exec -it --user=solr solr bin/solr create_core -c test -d sunspot
```

Not yet sure what to do with indexes as they should be stored outside Solr image I think.
I tried changing the `<dataDir>${solr.data.dir:}</dataDir>` to `<dataDir>/data/${solr.core.name:}</dataDir>` in `solrconfig.xml` and then mounting with `-v` but that does't work because it's mounted with root and I had to manually make it writable for `solr:solr`. Any suggestions on this?

**Comment by makuk66** [comment]
Creating a new docker image with your custom configsets sounds like a fine approach, but it'd be nice if we had a document solution with volumes too.

The permission problems you mentioned are a know issues with docker host-mounted data directories. See https://github.com/docker/docker/issues/7198 for a discussion. Workarounds are using the same UID in both host and master, or chowning from within the container; both unappealing. Using data volume containers may be more manageable. We could do with some examples.

**Comment by makuk66** [comment]
I have updated https://github.com/makuk66/docker-solr/blob/master/Docker-FAQ.md with an example of using data volume containers to store the data and config outside the container.
