### ISSUE TITLE
Tags keep updating

### ISSUE THREAD

**Issue by slobo** [makuk66/docker-solr#12]
Hi Martijn,
It would seem that images are not tag-stable. Say 5.2.1 gets refreshed every time you make a commit. Any chance you can introduce some tags that we can depend on image not being rebuilt?

**Comment by b-long** [comment]
:+1: I haven't observed this myself, but is it still an open issue?

**Comment by slobo** [comment]
I think now that this repo has been superseded by official _solr image, tags will stay stable :)

But I observe this a fair bit in docker land and we are forced to maintain our own images if we want the versions to be locked down. While most of the time, image rebuild doesn't meant anything had really changed, when working collection of systems all of a sudden starts misbehaving any moving part needs to be considered...

**Comment by makuk66** [comment]
In some ways this is a feature -- you can tweak a Dockerfile, or update to newer base images without the solr version changing, and get fixes without needing to change anything on your end; and because the solr version stays fixed, your interface should be unchanged too. But I agree, there are downsides too. I don't see a good way to address this from our side, especially now that we're in the official images. You can of course create your own local tags, but that's a bit of a faff, and doesn't help when pulling. I guess you could run your own registry and maintain your own tags there, but I've not tried that.

**Comment by slobo** [comment]
As Docker grows I suppose they will have to come up with some standard tag scheme where it will be possible to specify change tolerance all the way from 'latest at any cost' to 'this exact image, only with a nice name instead of hash'. Think semver etc. I'd be fine with specifying say patch levels for Dockerfile, eg `solr:5.2.1-p1`. Or say `solr:5.2.1@2016-12-13`. 

Right now it's a bit of a wild west, esp. with migration to alpine - witness all the `-alpine` official images that let you chose a base image for official packages.

Note, most of the time I'm quite happy to get a better running container with the same version of service, the only issue I have is that anyone can just swap anything and still use the same tag. As you suggest, it's all easily solvable by running private registries, but it would be nice to have the ability to always end up with 100% equivalent binaries no matter when I do a pull. Maybe it's expecting too much from a free public hub :)

Cheers
